package store.cadera.cdrjobs.listener;
import net.kyori.adventure.text.Component;import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.EntityExplodeEvent;import org.bukkit.entity.Player;import store.cadera.cdrjobs.CdrJobsPlugin;import store.cadera.cdrjobs.data.ProfessionStore;import store.cadera.cdrjobs.model.*;import store.cadera.cdrjobs.service.*;import java.util.*;
public final class LumberjackListener implements Listener {private static final Set<Material> ELDER=EnumSet.of(Material.DARK_OAK_LOG,Material.MANGROVE_LOG,Material.CHERRY_LOG);private final CdrJobsPlugin plugin;private final ProfessionStore store;private final ProgressionService progression;private final LumberjackService wood;private final LevelService levels;private Map<Material,Integer> xp=new HashMap<>();public LumberjackListener(CdrJobsPlugin p,ProfessionStore s,ProgressionService pr,LumberjackService w,LevelService l){plugin=p;store=s;progression=pr;wood=w;levels=l;refreshXpMap();}public void refreshXpMap(){xp=plugin.loadActivityXp("lumberjack.xp");}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void onPlace(BlockPlaceEvent e){if(plugin.getConfig().getBoolean("lumberjack.enabled",true)&&xp.containsKey(e.getBlockPlaced().getType()))store.markPlacedJobBlock(e.getBlockPlaced().getLocation(),LumberjackService.JOB);}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void onBreak(BlockBreakEvent e){if(!plugin.getConfig().getBoolean("lumberjack.enabled",true))return;Integer base=xp.get(e.getBlock().getType());if(base==null)return;if(store.consumePlacedJobBlock(e.getBlock().getLocation(),LumberjackService.JOB))return;Player p=e.getPlayer();wood.recordChop(p,ELDER.contains(e.getBlock().getType()));double mult=Math.max(0,plugin.getConfig().getDouble("lumberjack.xp-multiplier",1));long amount=wood.applyXp(p,Math.max(1,Math.round(base*mult)));JobProgress pr=progression.addXp(p,JobType.LUMBERJACK,amount);if(plugin.getConfig().getBoolean("settings.actionbar-xp",true)){long req=levels.xpRequiredForNextLevel(pr.level());p.sendActionBar(Component.text(pr.level()>=levels.maxLevel()?"✦ Ironbark Warden Lv."+levels.maxLevel()+" • MAX":"✦ Ironbark +"+amount+" XP • Lv."+pr.level()+" • "+pr.xp()+"/"+req));}}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void onExtend(BlockPistonExtendEvent e){if(!plugin.getConfig().getBoolean("lumberjack.anti-exploit.piston-tracking",true))return;List<Location>to=new ArrayList<>();for(Block b:e.getBlocks())if(xp.containsKey(b.getType())&&store.consumePlacedJobBlock(b.getLocation(),LumberjackService.JOB))to.add(b.getRelative(e.getDirection()).getLocation());to.forEach(l->store.markPlacedJobBlock(l,LumberjackService.JOB));}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void onRetract(BlockPistonRetractEvent e){if(!plugin.getConfig().getBoolean("lumberjack.anti-exploit.piston-tracking",true))return;List<Location>to=new ArrayList<>();for(Block b:e.getBlocks())if(xp.containsKey(b.getType())&&store.consumePlacedJobBlock(b.getLocation(),LumberjackService.JOB))to.add(b.getRelative(e.getDirection().getOppositeFace()).getLocation());to.forEach(l->store.markPlacedJobBlock(l,LumberjackService.JOB));}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void onBlockExplode(BlockExplodeEvent e){cleanup(e.blockList());}@EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void onEntityExplode(EntityExplodeEvent e){cleanup(e.blockList());}private void cleanup(List<Block>blocks){for(Block b:blocks)if(xp.containsKey(b.getType()))store.consumePlacedJobBlock(b.getLocation(),LumberjackService.JOB);}
}
