name: CdrJobs
version: '0.9.0'
main: store.cadera.cdrjobs.CdrJobsPlugin
api-version: '1.21'
author: CADERA
description: Fantasy profession progression system with public API by CADERA.
softdepend: [PlaceholderAPI]
commands:
  cdrjobs: { aliases: [jobs, cjobs], usage: /cdrjobs }
  cdrjobsadmin: { aliases: [cjobsadmin], permission: cdrjobs.admin }
permissions:
  cdrjobs.use: { default: true }
  cdrjobs.admin: { default: op }
